<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Search_Tab</name>
   <tag></tag>
   <elementGuidId>8b4aefe8-6196-4eb5-80dd-6f89b90655fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='spn_sr_tabpanel_contentActive']//span[text()='Search']</value>
   </webElementProperties>
</WebElementEntity>
